# Generated by Django 3.2.7 on 2021-10-25 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('capital', models.CharField(max_length=300, null=True)),
                ('population', models.IntegerField()),
                ('land_area', models.IntegerField()),
                ('population_density', models.IntegerField()),
                ('alpha_2', models.CharField(max_length=2, null=True)),
                ('alpha_3', models.CharField(max_length=3, null=True)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='countries.continent')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
