# Generated by Django 3.2.7 on 2022-09-15 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country2',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name_official', models.CharField(max_length=200)),
                ('name_common', models.CharField(max_length=200)),
                ('timezone', models.CharField(max_length=200)),
                ('independent', models.BooleanField(null=True)),
                ('domain', models.CharField(max_length=200, null=True)),
                ('un_member', models.BooleanField()),
                ('capital', models.CharField(max_length=200, null=True)),
                ('sub_region', models.CharField(max_length=200, null=True)),
                ('landlocked', models.BooleanField()),
                ('population', models.IntegerField()),
                ('area', models.FloatField()),
                ('coordinates', models.FloatField(null=True)),
                ('capital_coordinates', models.FloatField(null=True)),
                ('cca2', models.CharField(max_length=200, null=True)),
                ('cca3', models.CharField(max_length=200, null=True)),
                ('ccn3', models.CharField(max_length=200, null=True)),
                ('borders', models.CharField(max_length=200, null=True)),
                ('flag', models.CharField(max_length=200, null=True)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='countries.continent')),
            ],
            options={
                'ordering': ['name_official'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('capital', models.CharField(max_length=300, null=True)),
                ('population', models.IntegerField()),
                ('land_area', models.IntegerField()),
                ('population_density', models.IntegerField()),
                ('alpha_2', models.CharField(max_length=2, null=True)),
                ('alpha_3', models.CharField(max_length=3, null=True)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='countries.continent')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
